name: Build DosePolice EXE

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        os: [windows-2022]
        python-version: ['3.11']
    
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v4
      
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller reportlab customtkinter openpyxl
        
    - name: Build with PyInstaller
      run: |
        pyinstaller --onefile --windowed --icon=logo.ico --add-data "images;images" DosePolice.py --name DosePolice
        
    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: DosePolice_${{ matrix.os }}_Python${{ matrix.python-version }}
        path: dist/DosePolice.exe
